// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PulsoUrbano.Net.Data;

#nullable disable

namespace PulsoUrbano.Net.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SEQ_ALERTA_HISTORICO")
                .IncrementsBy(10);

            modelBuilder.HasSequence("SEQ_ZONA_REFERENCIA")
                .IncrementsBy(10);

            modelBuilder.Entity("PulsoUrbano.Net.Models.Entities.AlertaHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_ALERTA_HISTORICO");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CONFIRMADO");

                    b.Property<DateTime>("DtAlerta")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ALERTA");

                    b.Property<string>("NivelAlerta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("NIVEL_ALERTA");

                    b.Property<decimal>("No2Registrado")
                        .HasColumnType("NUMBER(8,4)")
                        .HasColumnName("NO2_REGISTRADO");

                    b.Property<decimal>("ScoreRegistrado")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("SCORE_REGISTRADO");

                    b.Property<string>("TextoRecomendacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("TEXTO_RECOMENDACAO");

                    b.Property<int>("ZonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONA");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId", "DtAlerta")
                        .HasDatabaseName("IX_ALERTA_ZONA_DT");

                    b.ToTable("ALERTA_HISTORICO", (string)null);
                });

            modelBuilder.Entity("PulsoUrbano.Net.Models.Entities.ZonaReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONA");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "SEQ_ZONA_REFERENCIA");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MUNICIPIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("ZONA_REFERENCIA_NET", (string)null);
                });

            modelBuilder.Entity("PulsoUrbano.Net.Models.Entities.AlertaHistorico", b =>
                {
                    b.HasOne("PulsoUrbano.Net.Models.Entities.ZonaReferencia", "Zona")
                        .WithMany("Alertas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("PulsoUrbano.Net.Models.Entities.ZonaReferencia", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
